### ISSUE TITLE
Unable to require("alloy/moment")

### ISSUE THREAD

**Issue by ssx** [aca-mobile/ti-unit#3]
I have a commonJS module within my app that uses the build in moment library within alloy. I can resolve the relative path issues within my commonJS requires() by setting the paths, however I don't actually know the path of the alloy/moment lib.

Any ideas on how I can require this when being called within a spec?

**Comment by davidcyp** [comment]
Do you have an example of your code and test? This can help me in getting a better understanding of your problem.

**Comment by ssx** [comment]
Hi David, of course, give me a moment!

**Comment by ssx** [comment]
File ./lib/core/generate.js

```javascript
var otherthing = require('./otherthing');
var moment = require ('alloy/moment');

exports.getEpoch = function() {
   return moment().unix();
}
```

I can require my module in a spec with:

```javascript
var generate = require("../app/lib/core/generate");
```

but when doing so, it fails because it can't then find alloy/moment.

**Comment by davidcyp** [comment]
Okay. And what exactly do you want to achieve? Do you a) want or need to use the real _moment_ implementation in your test? Or b) do you just want to interact with a _mocked moment_, just like you would do with _otherthing_? 

In the latter case, we would need to inject the mock. However, since you can also invoke moment like this _moment()_, it wouldn't be that easy to write the mock.
``` 
 var momentMock = ..;
 MockRequire = require('tiunit/mockrequire');
 MockRequire.addMock('alloy/moment', momentMock);
```
However I don't see yet how we would need to write the moment() mock. Maybe we could use this http://rafaelhz.github.io/testing-dates-jasmine/
 but I have to investigate it. I will also ask my teammates tomorrow how they handled moment.js in their tests, because I am quite sure they have used it in one of their projects. Feel free to ping me if I haven't commented on this thread before friday evening CET.

See https://github.com/aca-mobile/ti-unit/wiki/Mocking-injected-dependencies

**Comment by ssx** [comment]
Ideally, I could do with using the real implementation if possible! Otherwise I can take the mock route and go from there!

**Comment by davidcyp** [comment]
Okay Scott, what you can do. I have altered a test of ours to include a call to moment().unix(). I have also altered the test. Here is what I did. Note that this is just a solution to unlock you. I'll try to describe it and find an elegant solution for it later on:

```
    MockRequire = require('tiunit/mockrequire');

    var codeUnderTest;
    // real moment.js implementation, relative to position of spec folder
    var moment = require('../Resources/alloy/moment');

    beforeEach(function () {

        // or if you want to use a mock instead of the real 'moment' implementation
        /*
        MockRequire.addMock('alloy/moment', function(){ return {
            unix: function(){}
        }});
        */

        // first add the dependencies of codeUnderTest
        MockRequire.addMock('alloy/moment', moment);
       // now instantiate your codeUnderTest object
        codeUnderTest = require('../app/lib/code.under.test');
    });

```

**Comment by davidcyp** [comment]
Note that it might be interesting to mock your moment implementation. Otherwise you might get unpredictable results, or tests that depend of timezones or other randomness

**Comment by ssx** [comment]
Agreed on the latter point, I'll give that a go in a few moments, many thanks for the help! 😄

**Comment by ssx** [comment]
Having though on this more, I'm going to extract the parts of my lib that use moment in separated functions, then I can easily just mock those small few and everything else will function as expected. Once again, thanks for the help!

**Comment by davidcyp** [comment]
My pleasure. If there is any feedback you have on the library, please share, so we can improve it
